# compose.logs.yml
version: "3.9"

services:
  log-signer:
    image: ghcr.io/nesaorg/log-signer:latest   
    container_name: log-signer
    restart: unless-stopped
    environment:
      INGEST_URL: https://logs.nesa.ai/ingest   
      MONIKER: ${MONIKER}
      NODE_ID: ${NODE_ID}
      PUBLIC_IP: ${PUBLIC_IP}
      SEQ_STATE: /data/seq.sqlite
      BATCH_BYTES: "1048576"        
      BATCH_INTERVAL_MS: "2000"
      MAX_RETRY_BACKOFF_S: "60"
    volumes:
      - ./env:/env:ro
      - logsigner-data:/data
    secrets:
      - node_priv_key
    ports:
      - "127.0.0.1:8787:8787"       
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:8787/healthz"]
      interval: 10s
      timeout: 2s
      retries: 12

  log-collector:
    image: cr.fluentbit.io/fluent/fluent-bit:2.2
    container_name: log-collector
    restart: unless-stopped
    depends_on:
      - log-signer
    environment:
      MONIKER: ${MONIKER}
      NODE_ID: ${NODE_ID}
      PUBLIC_IP: ${PUBLIC_IP}
    volumes:
      # Docker JSON logs
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Docker API to fetch labels and container metadata
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Bootstrap installer log (created by bootstrap.sh)
      - ${HOME}/.nesa/logs:/host-logs:ro
      # Fluent Bit configs
      - ./logging/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./logging/parsers.conf:/fluent-bit/etc/parsers.conf:ro
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]

secrets:
  node_priv_key:
    file: ./env/.node_privkey

volumes:
  logsigner-data:

