services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  agent:
    extends:
      file: compose.agent.yml
      service: agent
  mysql:
    extends:
      file: compose.agent.yml
      service: mysql
  orchestrator:
    extends:
      file: compose.orchestrator.yml
      service: orchestrator
  mongodb:
    extends:
      file: compose.orchestrator.yml
      service: mongodb


volumes:
  ipfs-data:
  ipfs-staging:
  mysql-data:
  agent-config:
  mongodata:

networks:
  nesa:
    driver: bridge