services:
  agent:
    image: ghcr.io/nesaorg/agent:testnet-latest
    container_name: agent
    restart: unless-stopped
    env_file:
      - ./env/agent.env
    depends_on:
      mysql:
        condition: service_healthy
      ipfs:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/agent/config
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    command:
      - server
    networks:
      - nesa

  mysql:
    image: mysql:latest
    container_name: agent-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: agent
      MYSQL_USER: agent
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nesa
volumes:
  mysql-data: