services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nesa_user
      - MONGO_INITDB_ROOT_PASSWORD=nesa_pass
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - nesa
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/nesa --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  orchestrator:
    image: ghcr.io/nesaorg/orchestrator:testnet-latest
    container_name: orchestrator
    ports:
      - "31333:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - nesa
    env_file:
      - ./env/orchestrator.env
    environment:
      - MONGO_URI=mongodb://nesa_user:nesa_pass@mongodb:27017
    volumes:
      - ${HOME}/.nesa/cache:/root/.cache
     

volumes:
  mongodata:
  ipfs-data:
  ipfs-staging:

networks:
  nesa:
    driver: bridge