services:
  bsns-s:
    image: ghcr.io/nesaorg/bsns-s:testnet-latest 
    container_name: bsns-s
    restart: unless-stopped
    env_file:
      - ./env/bsns-s.env
    ports:
      - "31331:31331"
    networks:
      - nesa