services:
    orchestrator:
        extends:
            file: compose.community.yml
            service: orchestrator
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
    watchtower:
        extends:
            file: compose.community.yml
            service: watchtower

networks:
    nesa:
        driver: bridge
