services:
  log-signer:
    image: ghcr.io/nesaorg/devsigner:latest
    container_name: log-signer
    restart: unless-stopped
    user: "0:0"
    networks: [nesa]
    env_file:
      - ./env/base.env
      - ./env/orchestrator.env
    environment:
      INGEST_URL: ${INGEST_URL:-http://38.80.122.133:11444/ingest}
      BOOTSTRAP_LOG: ${BOOTSTRAP_LOG:-/hostlogs/bootstrap.log}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logging/log-harvest.sh:/usr/local/bin/log-harvest.sh:ro
      - ${HOME}/.nesa/logs:/hostlogs:ro
      - log-signer-state:/var/lib/log-signer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["/bin/sh", "-lc"]
    command: ["/usr/local/bin/log-harvest.sh"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pgrep -f '/usr/local/bin/devsigner' >/dev/null || pgrep -f 'docker events' >/dev/null",
        ]
      interval: 10s
      timeout: 3s
      retries: 10

networks:
  nesa:
    driver: bridge

volumes:
  log-signer-state: {}
