services:
  chain:
    image: ghcr.io/nesaorg/nesachain:testnet-latest 
    container_name: nesachain
    restart: unless-stopped
    env_file:
      - ./env/base.env
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
    volumes:
      - nesachain-data:/app/
    networks:
      - nesa

volumes:
  nesachain-data:
  
networks:
  nesa:

    driver: bridge
