version: '3.8'
services:
  dist-inf-server:
    image: ghcr.io/nesaorg/bsns/bsns-s:test
    container_name: bsns-s
    restart: always
    environment:
      - INITIAL_PEER=$INITIAL_PEER
    ports:
      - "31331:31331"
    networks:
      - nesa