services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  bsns-s:
    image: ghcr.io/nesaorg/bsns-s:testnet-latest 
    container_name: bsns-s
    restart: unless-stopped
    env_file:
      - ./env/base.env
      - ./env/bsns-s.env
    volumes:
      - ${HOME}/.nesa/identity:/identity 
    ports:
      - "31331:31331"
    networks:
      - nesa

volumes:
  ipfs-data:
  ipfs-staging:

networks:
  nesa:
    driver: bridge