services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  bsns-s:
    image: ghcr.io/nesaorg/bsns-s:testnet-latest 
    container_name: bsns-s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    env_file:
      - ./env/bsns-s.env
    volumes:
      - identity:/identity
    ports:
      - "31331:31331"
    networks:
      - nesa

volumes:
  identity:
  ipfs-data:
  ipfs-staging:

networks:
  nesa:
    driver: bridge