services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs

  orchestrator:
    extends:
      file: compose.orchestrator.yml
      service: orchestrator

    depends_on:
      - bsns-c

  bsns-c:
    extends:
      file: compose.bsns-c.yml
      service: bsns-c
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  identity:
  ipfs-data:
  ipfs-staging:

networks:
  nesa:
    driver: bridge
