services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  orchestrator:
    image: ghcr.io/nesaorg/orchestrator:testnet-latest
    container_name: orchestrator
    restart: unless-stopped
    networks:
      - nesa
    env_file:
      - ./env/base.env
      - ./env/orchestrator.env
    environment:
      PsUTIL_PROCFS_PATH: /host_proc
    volumes:
      - ${HOME}/.nesa/cache:/root/.cache
      - ./logs:/orchestrator/dist/logs
      - ${HOME}/.nesa/identity:/root/.nesa/identity
      - /proc:/host_proc:ro

volumes:
  ipfs-data:
  ipfs-staging:

networks:
  nesa:
    driver: bridge
