services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  bsns-s:
    extends:
      file: compose.bsns-s.yml
      service: bsns-s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  identity:
  ipfs-data:
  ipfs-staging:

networks:
  nesa:
    driver: bridge