services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  orchestrator:
    extends:
      file: compose.orchestrator.yml
      service: orchestrator

volumes:
  ipfs-data:
  ipfs-staging:

networks:
  nesa:
    driver: bridge
