services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  agent:
    extends:
      file: compose.agent.yml
      service: agent

  mysql:
    extends:
      file: compose.agent.yml
      service: mysql

  orchestrator:
    extends:
      file: compose.orchestrator.yml
      service: orchestrator

  mongodb:
    extends:
      file: compose.orchestrator.yml
      service: mongodb

  bsns-c: 
    image: ghcr.io/nesaorg/bsns-c:testnet-latest
    container_name: bsns-c
    restart: unless-stopped
    volumes:
      - identity:/identity
    depends_on:
      - orchestrator
    ports:
      - "31330:31330"
    networks:
      - nesa

volumes:
  identity:
  ipfs-data:
  ipfs-staging:
  mongodata:

networks:
  nesa:
    driver: bridge