services:
  bsns-s:
    image: ghcr.io/nesaorg/bsns/bsns-s:test
    container_name: bsns-s
    restart: unless-stopped
    environment:
      - INITIAL_PEER=$INITIAL_PEER
    ports:
      - "31331:31331"
    networks:
      - nesa