services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_node
    restart: unless-stopped
    command: ["daemon", "--enable-pubsub-experiment"]
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs 
      - ipfs-staging:/export
      - ./scripts/001_config_and_sub.sh:/container-init.d/001_config_and_sub.sh
    networks:
      - nesa

volumes:
    ipfs-data:
    ipfs-staging:

networks:
  nesa:
    driver: bridge