version: '3.8'
services:
  agent:
    extends:
      file: compose.agent.yml
      service: agent
  mysql:
    extends:
      file: compose.agent.yml
      service: mysql
  inf:
    image: ghcr.io/nesaorg/inf/inf:test
    container_name: inf
    restart: always
    depends_on:
      - agent
    ports:
      - "31333:31333"