services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  orchestrator:
    extends:
      file: compose.orchestrator.yml
      service: orchestrator
  mongodb:
    extends:
      file: compose.orchestrator.yml
      service: mongodb

volumes:
  ipfs-data:
  ipfs-staging:
  mongodata:

networks:
  nesa:
    driver: bridge
