version: '3.8'
services:
  agent:
    extends:
      file: compose.agent.yml
      service: agent
  mysql:
    extends:
      file: compose.agent.yml
      service: mysql
  orchestrator:
    extends:
      file: compose.orchestrator.yml
      service: orchestrator