services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  orchestrator:
    extends:
      file: compose.community.yml
      service: orchestrator
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
  mongodb:
    extends:
      file: compose.orchestrator.yml
      service: mongodb


volumes:
  ipfs-data:
  ipfs-staging:
  mongodata:
  identity:

networks:
  nesa:
    driver: bridge