services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  agent:
    image: ghcr.io/nesaorg/agent:testnet-latest
    container_name: agent
    restart: unless-stopped
    env_file:
      - ./env/base.env
      - ./env/agent.env
    depends_on:
      mysql:
        condition: service_healthy
      ipfs:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - agent-config:/app/config
    command:
      - server
    networks:
      - nesa

  mysql:
    image: mysql:latest
    container_name: agent-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: agent
      MYSQL_USER: agent
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d 
    networks:
      - nesa

volumes:
  ipfs-data:
  ipfs-staging:
  mysql-data:
  agent-config:

networks:
  nesa:
    driver: bridge