version: '3.8'
services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        GOBUILD: "go build"
        NAME: "agent"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    container_name: agent
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      ipfs:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/agent/config
    environment:
      - VIRTUAL_HOST=YOUR_DOMAIN_FOR_VHOST
      - LETSENCRYPT_HOST=YOUR_DOMAIN_FOR_LETSENCRYPT
      - LETSENCRYPT_EMAIL=YOUR_EMAIL_FOR_LETSENCRYPT
    command:
      - server

  mysql:
    image: mysql:latest
    container_name: agent-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: agent
      MYSQL_USER: agent
      MYSQL_PASSWORD: 123456
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: