version: '3.8'
services:
  agent:
    extends:
      file: compose.agent.yml
      service: agent

  mysql:
    extends:
      file: compose.agent.yml
      service: mysql

  orchestrator:
    extends:
      file: compose.orchestrator.yml
      service: orchestrator

  mongodb:
    extends:
      file: compose.orchestrator.yml
      service: mongodb

  dist-inf-client:
    image: ghcr.io/nesaorg/dist-inf/dist-inf-client:test
    container_name: dist-inf-client
    restart: always
    depends_on:
      - dist-orc
    ports:
      - "31330:31330"
    networks:
      - nesa
  
