services:
  ipfs:
    extends:
      file: compose.ipfs.yml
      service: ipfs
  orchestrator:
    extends:
      file: compose.orchestrator.yml
      service: orchestrator
    image: ghcr.io/nesaorg/orchestrator:devnet-latest
  watchtower:
    extends:
      file: compose.yml
      service: watchtower

volumes:
  ipfs-data:
  ipfs-staging:

networks:
  nesa:
    driver: bridge
