version: '3.8'
services:
  mysql:
    image: mariadb:10.6-focal
    container_name: agent-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: agent
      MYSQL_USER: agent
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./db/:/var/lib/mysql

  agent:
    image: ghcr.io/nesaorg/agent/agent:test
    container_name: agent
    restart: always
    depends_on:
      - mysql
    ports:
      - "17216:17216"
    volumes:
      - ./agent/conf.ini:/app/conf.ini
      - ./shared/:/app/shared

  nesachain:
    image: ghcr.io/nesaorg/nesachain/nesachain:test
    container_name: nesachain
    restart: always
    ports:
      - "1317:1317"
      - "26656:26656"
      - "26657:26657"
    volumes:
      - ./nesachain/genesis.json:/app/.nesachain/config/genesis.json
      - ./shared/:/app/shared
