name: Test Repository Dispatch by webhook
on:
  repository_dispatch:
    types: [trigger-build]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Run build
        run: echo "Build triggered via repository dispatch on branch main!"
      - name: Triggered
        run: echo "Triggered!"
